# Generated by Django 3.2.22 on 2024-01-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240107_0347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name_plural': 'CartItems'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_signature',
        ),
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='OrderedItems',
        ),
    ]
