# Generated by Django 3.2.22 on 2023-12-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='api.OrderItem', to='api.Product'),
        ),
    ]
