# Generated by Django 3.2.22 on 2024-01-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_quantity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_type',
        ),
        migrations.DeleteModel(
            name='QuantityVariant',
        ),
    ]
