# Generated by Django 3.2.22 on 2023-12-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20231229_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_name',
        ),
    ]
