# Generated by Django 3.2.22 on 2023-12-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_product_cartitem_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_name',
            new_name='product',
        ),
    ]
